
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-5pm-1
owner: ucsb-cs156-s24
repo_name: team01-s24-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjUwMDU1NzUz","is_bot":false,"login":"rtzhang1x","name":"rt.z"},"headRefName":"Rick-Location-Controller","number":20,"title":"Add functionality and tests for Location Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-1/pull/20"},{"author":{"id":"U_kgDOBX3i4Q","is_bot":false,"login":"Peak1260","name":"Peak"},"headRefName":"Peak-PublicHoliday","number":19,"title":"Finished Service and Controller for Public Holidays","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-1/pull/19"},{"author":{"id":"MDQ6VXNlcjUwMDU1NzUz","is_bot":false,"login":"rtzhang1x","name":"rt.z"},"headRefName":"Rick-Location","number":18,"title":"Add Location service and corresponding test bench","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-1/pull/18"}]
